x-redis-defaults: &redis-defaults
  image: redis:7-alpine
  restart: always
  networks:
    - internal

services:
  redis:
    <<: *redis-defaults
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]

  redis-event-stream:
    <<: *redis-defaults
    command:
      ["redis-cli", "-u", "redis://redis:6379/0", "PSUBSCRIBE", "events.*"]
    depends_on:
      - redis
