{
 "title": "MongoDB",
 "description": "Example Dashboard for Mongodb",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": "ict" }
  ]
 },
 "panels": [
  {
   "title": "MongoDB Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_up", "legendFormat": "__auto" }
   ]
  },
  { "title": "Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Query Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "mongodb_top_queries_count{database=\"$database\"}",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Total Document Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_document[$__rate_interval])",
     "legendFormat": "{{doc_op_type}}"
    }
   ]
  },
  {
   "title": "Scanned Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 13, "y": 5 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_queryExecutor_scannedObjects[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tasks Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Number of Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "mongodb_collstats_storageStats_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}