name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-push-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Tasks API: Build and push Docker image"
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: backend/tasks
          tags: |
            ghcr.io/${{ github.repository }}/tasks:latest
            ghcr.io/${{ github.repository }}/tasks:${{ github.sha }}

      - name: "Frontend: Build and push Docker image"
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: frontend
          tags: |
            ghcr.io/${{ github.repository }}/frontend:latest
            ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}

      - name: "Websocket Server: Build and push Docker image"
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: backend/websocket-server
          tags: |
            ghcr.io/${{ github.repository }}/websocket-server:latest
            ghcr.io/${{ github.repository }}/websocket-server:${{ github.sha }}
